# Site settings
title: Tatiana Merzhevich
description: My CV
favicon: https://raw.githubusercontent.com/tatiana-merz/tatiana-merz.github.io/d3335f3927e1b25fc9e6b2ced9098f46b829cce2/_site/assets/img/me.png
baseurl: https://tatiana-merz.github.io
url: https://tatiana-merz.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Tatiana Merzhevich
  title: Computational Linguist
  address: Stuttgart, Germany
  email: tatiana.merzhevich@gmail.com
  link: https://tatiana-merz.github.io/
  weibo:
  github: tatiana-merz
  linkedin: tatiana-merzhevich-3210b0235
  gavatar: https://raw.githubusercontent.com/tatiana-merz/tatiana-merz.github.io/d3335f3927e1b25fc9e6b2ced9098f46b829cce2/_site/assets/img/me.png
  workHistory:
    - work1:
      company: mine&make GmbH
      location: Stuttgart, Germany
      title: Computational Linguist
      started: 2022
      duration: (10/2022 - Present)
      description: • Validation and deployment NLP modules (NER, RE, Coreference)
                   • Linguistic research
                   • Frontend developmen
                   • Students supervision
    - work2:
      company: Universität Tübingen
      location: Tübingen, Germany
      title: Research Assistant
      started: 2022
      duration: (03/2021 – 09/2022)
      description:  • Data analysis (Pandas)
                    • Data visualisation (R, Tableau)
                    • Development of web applications (Shiny)
      description2: 
                    • Text processing (Python)
                    • Treebanks development
                    • Linguistic data collection
    - work3:
      company: Huawei
      location: Saint Petersburg, Russia
      title: Linguist
      started: 2019
      duration: (10/2019 – 02/2021)
      description: • Corpora design for a multilingual voice assistant
                   • Text annotation and normalization
                   • Data evaluation with MOS and unit test
  educationHistory:
    - education1:
      organization: Universität Tübingen
      location: Tübingen, Germany
      degree: MA
      major: Computational Linguistics
      started: 2019
      duration: (2019 - 2022)
    - education2:
      organization: State University of Aerospace Instrumentation
      location: Saint Petersburg, Russia
      degree: BA
      major: General Linguistics
      started: 2015
      duration: (2015 - 2019)
  languages:
    - language1:
      name: Russian
      proficiency: Native
    - language2:
      name: English
      proficiency: Advanced
    - language3:
      name: German
      proficiency: Intermediate
    - language4:
      name: Portuguese
      proficiency: Beginner
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: Transformers
      percentage: 100%
    - skill3:
      name: SpaCy
      percentage: 100%
    - skill4:
      name: SQL
      percentage: 90%
    - skill5:
      name: JavaScript
      percentage: 70%
